# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ace2eade5e80f3fdab1a63a37a2e7a7bd6722859d6019e3672bbc72038953a53831f5fb79511dbc6d25d34fa9452185785c7da73b299e402cd1c783fbcbb82e

test:
  secret_key_base: 8f8dc2ee621379f47ad41264a5d3b00aff402b08fe5381ebaf219ec7de250b1a4de61f5a8f4cfe53d376c4f72cf35e5a6cf01b7316c4af5b682e36355aa82ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
